import type { Player } from "@prisma/client";

export type SeedPlayer = Partial<
  Pick<Player, "name" | "position" | "team" | "rank">
>;

export const players: SeedPlayer[] = [
  {
    rank: 1,
    position: "RB",
    team: "Colts",
    name: "Jonathan Taylor",
  },
  {
    rank: 2,
    position: "RB",
    team: "Titans",
    name: "Derrick Henry",
  },
  {
    rank: 3,
    position: "RB",
    team: "Steelers",
    name: "Najee Harris",
  },
  {
    rank: 4,
    position: "RB",
    team: "Vikings",
    name: "Dalvin Cook",
  },
  {
    rank: 5,
    position: "WR",
    team: "Rams",
    name: "Cooper Kupp",
  },
  {
    rank: 6,
    position: "RB",
    team: "Chargers",
    name: "Austin Ekeler",
  },
  {
    rank: 7,
    position: "RB",
    team: "Browns",
    name: "Nick Chubb",
  },
  {
    rank: 8,
    position: "RB",
    team: "Panthers",
    name: "Christian McCaffrey",
  },
  {
    rank: 9,
    position: "WR",
    team: "Vikings",
    name: "Justin Jefferson",
  },
  {
    rank: 10,
    position: "WR",
    team: "Bengals",
    name: "Ja'Marr Chase",
  },
  {
    rank: 11,
    position: "RB",
    team: "Saints",
    name: "Alvin Kamara",
  },
  {
    rank: 12,
    position: "RB",
    team: "Bengals",
    name: "Joe Mixon",
  },
  {
    rank: 13,
    position: "TE",
    team: "Chiefs",
    name: "Travis Kelce",
  },
  {
    rank: 14,
    position: "TE",
    team: "Ravens",
    name: "Mark Andrews",
  },
  {
    rank: 15,
    position: "WR",
    team: "Buccaneers",
    name: "Mike Evans",
  },
  {
    rank: 16,
    position: "WR",
    team: "Cowboys",
    name: "CeeDee Lamb",
  },
  {
    rank: 17,
    position: "WR",
    team: "Bills",
    name: "Stefon Diggs",
  },
  {
    rank: 18,
    position: "WR",
    team: "Raiders",
    name: "Davante Adams",
  },
  {
    rank: 19,
    position: "RB",
    team: "Broncos",
    name: "Javonte Williams",
  },
  {
    rank: 20,
    position: "RB",
    team: "Lions",
    name: "D'Andre Swift",
  },
  {
    rank: 21,
    position: "RB",
    team: "Ravens",
    name: "JK Dobbins",
  },
  {
    rank: 22,
    position: "WR",
    team: "Chargers",
    name: "Mike Williams",
  },
  {
    rank: 23,
    position: "WR",
    team: "Dolphins",
    name: "Tyreek Hill",
  },
  {
    rank: 24,
    position: "WR",
    team: "49ers",
    name: "Deebo Samuel",
  },
  {
    rank: 25,
    position: "RB",
    team: "Cowboys",
    name: "Ezekiel Elliott",
  },
  {
    rank: 26,
    position: "RB",
    team: "Giants",
    name: "Saquon Barkley",
  },
  {
    rank: 27,
    position: "QB",
    team: "Bills",
    name: "Josh Allen",
  },
  {
    rank: 28,
    position: "RB",
    team: "Rams",
    name: "Cam Akers",
  },
  {
    rank: 29,
    position: "RB",
    team: "Buccaneers",
    name: "Leonard Fournette",
  },
  {
    rank: 30,
    position: "TE",
    team: "Falcons",
    name: "Kyle Pitts",
  },
  {
    rank: 31,
    position: "RB",
    team: "49ers",
    name: "Elijah Mitchell",
  },
  {
    rank: 32,
    position: "RB",
    team: "Cardinals",
    name: "James Conner",
  },
  {
    rank: 33,
    position: "WR",
    team: "Eagles",
    name: "A.J. Brown",
  },
  {
    rank: 34,
    position: "WR",
    team: "Seahawks",
    name: "DK Metcalf",
  },
  {
    rank: 35,
    position: "WR",
    team: "Chargers",
    name: "Keenan Allen",
  },
  {
    rank: 36,
    position: "TE",
    team: "49ers",
    name: "George Kittle",
  },
  {
    rank: 37,
    position: "RB",
    team: "Packers",
    name: "Aaron Jones",
  },
  {
    rank: 38,
    position: "WR",
    team: "Commanders",
    name: "Terry McLaurin",
  },
  {
    rank: 39,
    position: "WR",
    team: "Bengals",
    name: "Tee Higgins",
  },
  {
    rank: 40,
    position: "WR",
    team: "Steelers",
    name: "Diontae Johnson",
  },
  {
    rank: 41,
    position: "RB",
    team: "Patriots",
    name: "Damien Harris",
  },
  {
    rank: 42,
    position: "RB",
    team: "Jaguars",
    name: "Travis Etienne Jr.",
  },
  {
    rank: 43,
    position: "RB",
    team: "Chiefs",
    name: "Clyde Edwards-Helaire",
  },
  {
    rank: 44,
    position: "QB",
    team: "Chargers",
    name: "Justin Herbert",
  },
  {
    rank: 45,
    position: "TE",
    team: "Raiders",
    name: "Darren Waller",
  },
  {
    rank: 46,
    position: "QB",
    team: "Chiefs",
    name: "Patrick Mahomes",
  },
  {
    rank: 47,
    position: "WR",
    team: "Panthers",
    name: "DJ Moore",
  },
  {
    rank: 48,
    position: "WR",
    team: "Colts",
    name: "Michael Pittman Jr.",
  },
  {
    rank: 49,
    position: "RB",
    team: "Raiders",
    name: "Josh Jacobs",
  },
  {
    rank: 50,
    position: "RB",
    team: "Bears",
    name: "David Montgomery",
  },
  {
    rank: 51,
    position: "RB",
    team: "Commanders",
    name: "Antonio Gibson",
  },
  {
    rank: 52,
    position: "WR",
    team: "Bears",
    name: "Darnell Mooney",
  },
  {
    rank: 53,
    position: "WR",
    team: "Cardinals",
    name: "Marquise Brown",
  },
  {
    rank: 54,
    position: "WR",
    team: "Broncos",
    name: "Courtland Sutton",
  },
  {
    rank: 55,
    position: "RB",
    team: "Jets",
    name: "Breece Hall",
  },
  {
    rank: 56,
    position: "WR",
    team: "Saints",
    name: "Michael Thomas",
  },
  {
    rank: 57,
    position: "WR",
    team: "Texans",
    name: "Brandin Cooks",
  },
  {
    rank: 58,
    position: "WR",
    team: "Dolphins",
    name: "Jaylen Waddle",
  },
  {
    rank: 59,
    position: "QB",
    team: "Cardinals",
    name: "Kyler Murray",
  },
  {
    rank: 60,
    position: "WR",
    team: "Broncos",
    name: "Jerry Jeudy",
  },
  {
    rank: 61,
    position: "WR",
    team: "Eagles",
    name: "DeVonta Smith",
  },
  {
    rank: 62,
    position: "WR",
    team: "Lions",
    name: "Amon-Ra St. Brown",
  },
  {
    rank: 63,
    position: "QB",
    team: "Bengals",
    name: "Joe Burrow",
  },
  {
    rank: 64,
    position: "QB",
    team: "Eagles",
    name: "Jalen Hurts",
  },
  {
    rank: 65,
    position: "QB",
    team: "Ravens",
    name: "Lamar Jackson",
  },
  {
    rank: 66,
    position: "WR",
    team: "Bills",
    name: "Gabriel Davis",
  },
  {
    rank: 67,
    position: "WR",
    team: "Rams",
    name: "Allen Robinson II",
  },
  {
    rank: 68,
    position: "TE",
    team: "Cowboys",
    name: "Dalton Schultz",
  },
  {
    rank: 69,
    position: "RB",
    team: "Cowboys",
    name: "Tony Pollard",
  },
  {
    rank: 70,
    position: "RB",
    team: "Packers",
    name: "AJ Dillon",
  },
  {
    rank: 71,
    position: "RB",
    team: "Eagles",
    name: "Miles Sanders",
  },
  {
    rank: 72,
    position: "WR",
    team: "Jets",
    name: "Elijah Moore",
  },
  {
    rank: 73,
    position: "WR",
    team: "Buccaneers",
    name: "Chris Godwin",
  },
  {
    rank: 74,
    position: "RB",
    team: "Browns",
    name: "Kareem Hunt",
  },
  {
    rank: 75,
    position: "QB",
    team: "Cowboys",
    name: "Dak Prescott",
  },
  {
    rank: 76,
    position: "WR",
    team: "Ravens",
    name: "Rashod Bateman",
  },
  {
    rank: 77,
    position: "WR",
    team: "Titans",
    name: "Robert Woods",
  },
  {
    rank: 78,
    position: "WR",
    team: "Browns",
    name: "Amari Cooper",
  },
  {
    rank: 79,
    position: "TE",
    team: "Lions",
    name: "T.J. Hockenson",
  },
  {
    rank: 80,
    position: "RB",
    team: "Seahawks",
    name: "Kenneth Walker III",
  },
  {
    rank: 81,
    position: "QB",
    team: "Buccaneers",
    name: "Tom Brady",
  },
  {
    rank: 82,
    position: "QB",
    team: "Rams",
    name: "Matthew Stafford",
  },
  {
    rank: 83,
    position: "TE",
    team: "Bills",
    name: "Dawson Knox",
  },
  {
    rank: 84,
    position: "TE",
    team: "Patriots",
    name: "Hunter Henry",
  },
  {
    rank: 85,
    position: "QB",
    team: "Broncos",
    name: "Russell Wilson",
  },
  {
    rank: 86,
    position: "RB",
    team: "Dolphins",
    name: "Chase Edmonds",
  },
  {
    rank: 87,
    position: "RB",
    team: "Bills",
    name: "James Cook",
  },
  {
    rank: 88,
    position: "WR",
    team: "49ers",
    name: "Brandon Aiyuk",
  },
  {
    rank: 89,
    position: "WR",
    team: "Seahawks",
    name: "Tyler Lockett",
  },
  {
    rank: 90,
    position: "RB",
    team: "Falcons",
    name: "Cordarrelle Patterson",
  },
  {
    rank: 91,
    position: "WR",
    team: "Raiders",
    name: "Hunter Renfrow",
  },
  {
    rank: 92,
    position: "QB",
    team: "Packers",
    name: "Aaron Rodgers",
  },
  {
    rank: 93,
    position: "QB",
    team: "Raiders",
    name: "Derek Carr",
  },
  {
    rank: 94,
    position: "WR",
    team: "Chiefs",
    name: "JuJu Smith-Schuster",
  },
  {
    rank: 95,
    position: "WR",
    team: "Vikings",
    name: "Adam Thielen",
  },
  {
    rank: 96,
    position: "RB",
    team: "Seahawks",
    name: "Rashaad Penny",
  },
  {
    rank: 97,
    position: "WR",
    team: "Buccaneers",
    name: "Julio Jones",
  },
  {
    rank: 98,
    position: "WR",
    team: "Cowboys",
    name: "Michael Gallup",
  },
  {
    rank: 99,
    position: "WR",
    team: "Jaguars",
    name: "Christian Kirk",
  },
  {
    rank: 100,
    position: "WR",
    team: "Cardinals",
    name: "DeAndre Hopkins",
  },
  {
    rank: 101,
    position: "QB",
    team: "49ers",
    name: "Trey Lance",
  },
  {
    rank: 102,
    position: "RB",
    team: "Patriots",
    name: "Rhamondre Stevenson",
  },
  {
    rank: 103,
    position: "RB",
    team: "Bills",
    name: "Devin Singletary",
  },
  {
    rank: 104,
    position: "RB",
    team: "Texans",
    name: "Dameon Pierce",
  },
  {
    rank: 105,
    position: "RB",
    team: "Jaguars",
    name: "James Robinson",
  },
  {
    rank: 106,
    position: "RB",
    team: "Jets",
    name: "Michael Carter",
  },
  {
    rank: 107,
    position: "RB",
    team: "Broncos",
    name: "Melvin Gordon III",
  },
  {
    rank: 108,
    position: "TE",
    team: "Steelers",
    name: "Pat Freiermuth",
  },
  {
    rank: 109,
    position: "WR",
    team: "Falcons",
    name: "Drake London",
  },
  {
    rank: 110,
    position: "TE",
    team: "Eagles",
    name: "Dallas Goedert",
  },
  {
    rank: 111,
    position: "TE",
    team: "Cardinals",
    name: "Zach Ertz",
  },
  {
    rank: 112,
    position: "QB",
    team: "Vikings",
    name: "Kirk Cousins",
  },
  {
    rank: 113,
    position: "WR",
    team: "Packers",
    name: "Allen Lazard",
  },
  {
    rank: 114,
    position: "WR",
    team: "Titans",
    name: "Treylon Burks",
  },
  {
    rank: 115,
    position: "WR",
    team: "Steelers",
    name: "Chase Claypool",
  },
  {
    rank: 116,
    position: "RB",
    team: "Vikings",
    name: "Alexander Mattison",
  },
  {
    rank: 117,
    position: "RB",
    team: "Bears",
    name: "Khalil Herbert",
  },
  {
    rank: 118,
    position: "RB",
    team: "Rams",
    name: "Darrell Henderson Jr.",
  },
  {
    rank: 119,
    position: "TE",
    team: "Vikings",
    name: "Irv Smith Jr.",
  },
  {
    rank: 120,
    position: "WR",
    team: "Chiefs",
    name: "Marquez Valdes-Scantling",
  },
  {
    rank: 121,
    position: "WR",
    team: "Jets",
    name: "Garrett Wilson",
  },
  {
    rank: 122,
    position: "WR",
    team: "Patriots",
    name: "Jakobi Meyers",
  },
  {
    rank: 123,
    position: "WR",
    team: "Saints",
    name: "Chris Olave",
  },
  {
    rank: 124,
    position: "TE",
    team: "Commanders",
    name: "Logan Thomas",
  },
  {
    rank: 125,
    position: "TE",
    team: "Dolphins",
    name: "Mike Gesicki",
  },
  {
    rank: 126,
    position: "QB",
    team: "Bears",
    name: "Justin Fields",
  },
  {
    rank: 127,
    position: "RB",
    team: "Lions",
    name: "Jamaal Williams",
  },
  {
    rank: 128,
    position: "RB",
    team: "Ravens",
    name: "Gus Edwards",
  },
  {
    rank: 129,
    position: "QB",
    team: "Saints",
    name: "Jameis Winston",
  },
  {
    rank: 130,
    position: "WR",
    team: "Patriots",
    name: "DeVante Parker",
  },
  {
    rank: 131,
    position: "WR",
    team: "Bengals",
    name: "Tyler Boyd",
  },
  {
    rank: 132,
    position: "QB",
    team: "Dolphins",
    name: "Tua Tagovailoa",
  },
  {
    rank: 133,
    position: "WR",
    team: "Chiefs",
    name: "Skyy Moore",
  },
  {
    rank: 134,
    position: "TE",
    team: "Packers",
    name: "Robert Tonyan",
  },
  {
    rank: 135,
    position: "TE",
    team: "Bears",
    name: "Cole Kmet",
  },
  {
    rank: 136,
    position: "RB",
    team: "Buccaneers",
    name: "Rachaad White",
  },
  {
    rank: 137,
    position: "RB",
    team: "Falcons",
    name: "Tyler Allgeier",
  },
  {
    rank: 138,
    position: "TE",
    team: "Buccaneers",
    name: "Cameron Brate",
  },
  {
    rank: 139,
    position: "QB",
    team: "Jaguars",
    name: "Trevor Lawrence",
  },
  {
    rank: 140,
    position: "WR",
    team: "Giants",
    name: "Kenny Golladay",
  },
  {
    rank: 141,
    position: "WR",
    team: "Lions",
    name: "DJ Chark",
  },
  {
    rank: 142,
    position: "WR",
    team: "Cardinals",
    name: "Rondale Moore",
  },
  {
    rank: 143,
    position: "WR",
    team: "Steelers",
    name: "George Pickens",
  },
  {
    rank: 144,
    position: "WR",
    team: "Packers",
    name: "Romeo Doubs",
  },
  {
    rank: 145,
    position: "WR",
    team: "Patriots",
    name: "Nelson Agholor",
  },
  {
    rank: 146,
    position: "RB",
    team: "Texans",
    name: "Rex Burkhead",
  },
  {
    rank: 147,
    position: "WR",
    team: "Rams",
    name: "Van Jefferson",
  },
  {
    rank: 148,
    position: "WR",
    team: "Lions",
    name: "Jameson Williams",
  },
  {
    rank: 149,
    position: "QB",
    team: "Colts",
    name: "Matt Ryan",
  },
  {
    rank: 150,
    position: "QB",
    team: "Titans",
    name: "Ryan Tannehill",
  },
  {
    rank: 151,
    position: "WR",
    team: "Chiefs",
    name: "Mecole Hardman",
  },
  {
    rank: 152,
    position: "WR",
    team: "Chargers",
    name: "Joshua Palmer",
  },
  {
    rank: 153,
    position: "DST",
    team: "Buffalo Bills",
    name: "Buffalo Bills defense",
  },
  {
    rank: 154,
    position: "RB",
    team: "Dolphins",
    name: "Raheem Mostert",
  },
  {
    rank: 155,
    position: "WR",
    team: "Saints",
    name: "Jarvis Landry",
  },
  {
    rank: 156,
    position: "WR",
    team: "Broncos",
    name: "K.J. Hamler",
  },
  {
    rank: 157,
    position: "WR",
    team: "Jaguars",
    name: "Marvin Jones Jr.",
  },
  {
    rank: 158,
    position: "DST",
    team: "Dallas Cowboys",
    name: "Dallas Cowboys defense",
  },
  {
    rank: 159,
    position: "WR",
    team: "Giants",
    name: "Kadarius Toney",
  },
  {
    rank: 160,
    position: "QB",
    team: "Jets",
    name: "Zach Wilson",
  },
  {
    rank: 161,
    position: "RB",
    team: "Eagles",
    name: "Kenneth Gainwell",
  },
  {
    rank: 162,
    position: "DST",
    team: "Tampa Bay Buccaneers",
    name: "Tampa Bay Buccaneers defense",
  },
  {
    rank: 163,
    position: "DST",
    team: "San Francisco 49ers",
    name: "San Francisco 49ers defense",
  },
  {
    rank: 164,
    position: "TE",
    team: "Rams",
    name: "Tyler Higbee",
  },
  {
    rank: 165,
    position: "WR",
    team: "Bills",
    name: "Isaiah McKenzie",
  },
  {
    rank: 166,
    position: "QB",
    team: "Giants",
    name: "Daniel Jones",
  },
  {
    rank: 167,
    position: "WR",
    team: "Packers",
    name: "Sammy Watkins",
  },
  {
    rank: 168,
    position: "TE",
    team: "Broncos",
    name: "Albert Okwuegbunam",
  },
  {
    rank: 169,
    position: "TE",
    team: "Seahawks",
    name: "Noah Fant",
  },
  {
    rank: 170,
    position: "WR",
    team: "Vikings",
    name: "K.J. Osborn",
  },
  {
    rank: 171,
    position: "WR",
    team: "Commanders",
    name: "Jahan Dotson",
  },
  {
    rank: 172,
    position: "QB",
    team: "Panthers",
    name: "Baker Mayfield",
  },
  {
    rank: 173,
    position: "DST",
    team: "Denver Broncos",
    name: "Denver Broncos defense",
  },
  {
    rank: 174,
    position: "DST",
    team: "New England Patriots",
    name: "New England Patriots defense",
  },
  {
    rank: 175,
    position: "RB",
    team: "Commanders",
    name: "J.D. McKissic",
  },
  {
    rank: 176,
    position: "WR",
    team: "Panthers",
    name: "Robbie Anderson",
  },
  {
    rank: 177,
    position: "QB",
    team: "Commanders",
    name: "Carson Wentz",
  },
  {
    rank: 178,
    position: "DST",
    team: "Indianapolis Colts",
    name: "Indianapolis Colts defense",
  },
  {
    rank: 179,
    position: "DST",
    team: "Miami Dolphins",
    name: "Miami Dolphins defense",
  },
  {
    rank: 180,
    position: "RB",
    team: "Colts",
    name: "Nyheim Hines",
  },
  {
    rank: 181,
    position: "RB",
    team: "Cardinals",
    name: "Darrel Williams",
  },
  {
    rank: 182,
    position: "RB",
    team: "Chiefs",
    name: "Isiah Pacheco",
  },
  {
    rank: 183,
    position: "RB",
    team: "Chargers",
    name: "Isaiah Spiller",
  },
  {
    rank: 184,
    position: "RB",
    team: "Raiders",
    name: "Zamir White",
  },
  {
    rank: 185,
    position: "RB",
    team: "Commanders",
    name: "Brian Robinson Jr.",
  },
  {
    rank: 186,
    position: "RB",
    team: "Chargers",
    name: "Joshua Kelley",
  },
  {
    rank: 187,
    position: "RB",
    team: "Patriots",
    name: "Pierre Strong Jr.",
  },
  {
    rank: 188,
    position: "RB",
    team: "Rams",
    name: "Kyren Williams",
  },
  {
    rank: 189,
    position: "TE",
    team: "Colts",
    name: "Mo Alie-Cox",
  },
  {
    rank: 190,
    position: "WR",
    team: "49ers",
    name: "Jauan Jennings",
  },
  {
    rank: 191,
    position: "DST",
    team: "Los Angeles Rams",
    name: "Los Angeles Rams defense",
  },
  {
    rank: 192,
    position: "DST",
    team: "New Orleans Saints",
    name: "New Orleans Saints defense",
  },
  {
    rank: 193,
    position: "WR",
    team: "Cowboys",
    name: "Jalen Tolbert",
  },
  {
    rank: 194,
    position: "DST",
    team: "Baltimore Ravens",
    name: "Baltimore Ravens defense",
  },
  {
    rank: 195,
    position: "DST",
    team: "Los Angeles Chargers",
    name: "Los Angeles Chargers defense",
  },
  {
    rank: 196,
    position: "DST",
    team: "Philadelphia Eagles",
    name: "Philadelphia Eagles defense",
  },
  {
    rank: 197,
    position: "DST",
    team: "Cleveland Browns",
    name: "Cleveland Browns defense",
  },
  {
    rank: 198,
    position: "WR",
    team: "Colts",
    name: "Alec Pierce",
  },
  {
    rank: 199,
    position: "WR",
    team: "Packers",
    name: "Christian Watson",
  },
  {
    rank: 200,
    position: "WR",
    team: "Jets",
    name: "Corey Davis",
  },
];
